export const tableName = {
  BIRTHWAVE_CONTACTS: "birthwave_contacts",
  CLIENTS: "clients",
  MANAGEMENT: "managements",
  VLSLAWPRACTISE: "vls_law_practices",
  VLSLAWACADEMY: "vls_academys",
  VLSLAWAIBE: "vls_aibes",
  VLSLAWPROPERTY: "vls_property_laws",
  VLSLAWFAMILY: "vls_family_laws",
  VLS_MACT_MASTER_CLASS: "vls_mact_master_class_leads",
  VLS_CONSUMER_PROTECTION_LAW_MASTER_CLASS: "vls_consumer_protection_law_master_classes",
  VLS_DOP_AI_ASSISTED: "vls_dop_ai_assisted",
  VLS_AI_FOR_ADVOCATES: "vls_ai_for_advocates",
  VLS_TAXATION_LAW: "vls_taxation_law_leads",
  VLS_BUSINESS_LAW: "vls_business_law_leads",
  PIXELEYE: "pixel_eyes",
  PIXELEYE_WEBSITE_LEADS: "pixel_eye_website_leads",
  PIXELEYE_LEAD_STATE: "pixel_eye_lead_states",
  PIXELEYE_FOLLOW_UP_HISTORY: "pixel_eye_follow_up_history",
  PIXELEYE_CALL_LOGS: "pixel_eye_call_logs",
  PIXELEYE_FOLLOW_UP_CALL_COMPLIANCE: "pixel_eye_follow_up_call_compliance",
  AARAV_EYE_CARE: "aarav_eye_care_leads",
  ANTARDRASHTI_NETRALAYA: "antardrashti_netralaya_leads",
  RIO: "rio_leads",
  RIO_VACCINE_CHART: "rio_vaccine_chart_leads",
  SHANTI_EYE_TECH: 'shanti_eye_tech_leads',
  PHOENIX_FITNESS: 'phoenix_fitness_leads',
  API_LOGS: 'api_logs',
  INTEGRATION_WEBHOOK_EVENTS: 'integration_webhook_events',
  BIRTHWAVE_DOCTORS: 'birthwave_doctors',
  BIRTHWAVE_LEADS: 'birthwave_leads',
  BIRTHWAVE_APPOINTMENTS: 'birthwave_appointments',
  BIRTHWAVE_LEAD_ACTIVITIES: 'birthwave_lead_activities',
  BIRTHWAVE_WEBSITE_LEADS: 'birthwave_website_leads',
  BIRTHWAVE_TEAMS: 'birthwave_teams',
  BIRTHWAVE_TEAM_MEMBERS: 'birthwave_team_members',
  BIRTHWAVE_LEAD_ASSIGNMENTS: 'birthwave_lead_assignments',
  BIRTHWAVE_ASSIGNMENT_CURSORS: 'birthwave_assignment_cursors',
  BIRTHWAVE_ASSIGNMENT_RULES: 'birthwave_assignment_rules',
  BIRTHWAVE_SERVICES: 'birthwave_services',
  BIRTHWAVE_TASKS: 'birthwave_tasks',
  BIRTHWAVE_DISPOSITIONS: 'birthwave_dispositions',
  BIRTHWAVE_ATTENTION_ITEMS: 'birthwave_attention_items',
  CRM_CUSTOM_FIELDS: 'crm_custom_fields',
  CRM_CALLS: 'crm_calls',
  CRM_INTEGRATIONS: 'crm_integrations',
  CRM_FIELD_MAPPINGS: 'crm_field_mappings',
};







